#debug: true

spring:
  application:
    name: analytics

dns:
  hosts:
    root: localhost
server:
  hostname: ${dns.hosts.root}
  ssl:
    enabled: false
    trust-store: classpath:keystores/truststore.jks
    trust-store-password: changeit
    key-store: classpath:keystores/keystore.jks
    key-store-password: changeit
    key-password: ${server.ssl.key-store-password}
    client-certs-key-alias: ${server.hostname}
    jwk-key-store: classpath:keystores/jwksstore.pfx
    jwk-key-store-password: changeit
    self-signed:
      ca-alias: obri-internal-ca
  port: 9443

#Metrics configuration
metrics:
  port: 8444
  endpoints:
    root: https://metrics-services:${metrics.port}
    endpoint-usage:
      add-entries: ${metrics.endpoints.root}/api/kpi/endpoint-usage/add-entries
    jwts-generation:
      add-entries: ${metrics.endpoints.root}/api/kpi/jwts/jwts-generation/add-entries
    jwts-validation:
      add-entries: ${metrics.endpoints.root}/api/kpi/jwts/jwts-validation/add-entries


ob:
  auth:
    session:
      token-lifetime: 7 #days
      issuer-id: ${spring.application.name}
      cookie:
        domains: ${dns.hosts.root}
    oidc:
      idp:
        issuerid: "https://am.${dns.hosts.root}/oauth2/realms/root/realms/auth"
        jwk-uri: ${am.internal.root}/oauth2/realms/root/realms/auth/connect/jwk_uri
        authorize: ${am.internal.root}/oauth2/realms/root/realms/auth/authorize
      client:
        client-id: metrics
        redirect-uri: "https://${dns.hosts.root}:4206/redirectOpenId"


#JKWMS configuration
jwkms:
  root: https://${server.hostname}:${server.port}
  tan: openbanking.org.uk
  certificate:
    ou: forgerock.financial
    o: ForgeRock
    l: Bristol
    st: Avon
    c: UK
  jwkMsId: jwkms
  app-auth-header: X-APP
  rotationScheduler: "0 0 1 * * *"
  keysCleanup: "0 0 1 * * *"
  transport:
    algorithm: PS256
  signing:
    algorithm: PS256
  encryption:
    algorithm: RSA-OAEP-256
  encryptionMethod: A128CBC_HS256
  ExpirationWindowInMillis: 7200
  rotation:
    transport: 7776000000
    keys: 7776000000
  internalCAAlias: obri-internal-ca
  defaultCAAlias: obri-external-ca
  forgerock-applications:
    - name: aspsp
      group: as.aspsp.${dns.hosts.root}, rs.aspsp.${dns.hosts.root}, rcs.aspsp.${dns.hosts.root}, simulator.rs.${dns.hosts.root}, service.bank.${dns.hosts.root}, rs-store.aspsp.${dns.hosts.root}


## TO DELETE
am:
  trusted-header-certificate: ebJ8Qo7p9MpAIVenixCsNiDySmWEKb
  port: 443
  internal-port: 8443
  hostname: as.aspsp.${dns.hosts.root}
  matls-hostname: matls.as.aspsp.${dns.hosts.root}
  root: https://${am.hostname}
  authentication:
    chain: urn:openbanking:psd2:sca
  cookie:
    name: iPlanetDirectoryPro
  endpoint:
    login: ${am.root}/login
    logout: ${am.root}/logout
    userprofile: ${am.root}/json/users?_action=idFromSession
    users: ${am.root}/json/realms/root/realms/openbanking/users/
    registration: ${am.root}/json/realms/root/realms/openbanking/selfservice/userRegistration?_action=submitRequirements
  oidc:
    endpoint:
      accesstoken: ${am.internal.root}/oauth2/realms/root/realms/openbanking/access_token
      authorization: ${am.internal.root}/oauth2/realms/root/realms/openbanking/authorize
      userinfo: ${am.internal.root}/oauth2/realms/root/realms/openbanking/userinfo
      registration: ${am.internal.root}/oauth2/realms/root/realms/openbanking/register
    issuerid: ${am.root}/oauth2
    audiences: https://${am.matls-hostname}/oauth2, ${am.root}/oauth2, https://${am.matls-hostname}/oauth2/access_token"
    jwksuri: ${am.internal.root}/oauth2/realms/root/realms/openbanking/connect/jwk_uri
  userprofile:
    id: id
  realm:
    auth:
      hostname: am.${dns.hosts.root}
      oidc:
        issuerid: https://${am.realm.auth.hostname}/oauth2/realms/root/realms/auth
        jwk_uri: https://${am.realm.auth.hostname}/oauth2/realms/root/realms/auth/connect/jwk_uri
        authorize: https://${am.realm.auth.hostname}/oauth2/realms/root/realms/auth/authorize
  internal:
    root: https://openam:443
    oidc:
      issuerid: ${am.internal.root}/oauth2/auth
      endpoint:
        accesstoken: ${am.internal.root}/oauth2/realms/root/realms/auth/access_token
    endpoint:
      oidc-client: ${am.internal.root}/json/realms/root/realms/openbanking/realm-config/agents/OAuth2Client
      authentication: ${am.internal.root}/json/authenticate
    credential:
      amadmin: sy95jyiquqvjbbquq845gncysh13eax6 # TODO this is a default that shouldn't need to be here. All apps need it but may not use it.#obri

scgw:
  port: 8074

#Swagger config
#Swagger
swagger:
  license: "open-licence"
  license-url: "https://www.openbanking.org.uk/open-licence"
  terms-of-service-url: "https://backstage.forgerock.com/knowledge/openbanking/article/a45894685"
  version: "v3.1.1"
  contact:
    name: "ForgeRock AS"
    url: "https://${dns.hosts.root}"
    email: "openbanking-support@forgerock.com"
  title: "Analytics"
  description: "Analytics"

