name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check Copyright
      uses: qcastel/github-actions-maven-cmd@master
      with:
        maven-repo-server-id: forgerock-private-releases
        maven-repo-server-username: ${{ secrets.FR_PRIVATE_REPO_USER }}
        maven-repo-server-password: ${{ secrets.FR_PRIVATE_REPO_PASSWORD }}
        maven-args: "license:check"
    - name: Build and Test
      uses: qcastel/github-actions-maven-cmd@master
      with:
        maven-repo-server-id: forgerock-private-releases
        maven-repo-server-username: ${{ secrets.FR_PRIVATE_REPO_USER }}
        maven-repo-server-password: ${{ secrets.FR_PRIVATE_REPO_PASSWORD }}
        maven-args: "verify"
    - name: Temporarily disable "include administrators" branch protection
      uses: benjefferies/branch-protection-bot@master
      if: always()
      with:
        access-token: ${{ secrets.ACCESS_TOKEN }}
        owner: forgecloud
        repo: ob-tpp
    - name: Release
      uses: qcastel/github-actions-maven-release@master
      with:
        release-branch-name: "master"
        gpg-enabled: "true"
        gpg-key-id: ${{ secrets.GITHUB_GPG_KEY_ID }}
        gpg-key: ${{ secrets.GITHUB_GPG_KEY }}
        maven-repo-server-id: forgerock-private-releases
        maven-repo-server-username: ${{ secrets.FR_PRIVATE_REPO_USER }}
        maven-repo-server-password: ${{ secrets.FR_PRIVATE_REPO_PASSWORD }}
        maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip"
        git-release-bot-name: "openbankbot"
        git-release-bot-email: "openbankbot@forgerock.com"
        access-token: ${{ secrets.ACCESS_TOKEN }}
    - name: Enable "include administrators" branch protection
      uses: benjefferies/branch-protection-bot@master
      if: always()
      with:
        access-token: ${{ secrets.ACCESS_TOKEN }}
        owner: forgecloud
        repo: ob-tpp
