name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Set up maven
      run: curl https://raw.githubusercontent.com/ForgeCloud/ob-release/master/src/settings.xml > $M2_HOME/conf/settings.xml
    - name: Check Copyright	
      run: mvn -ntp license:check	
      env:	
        FR_PRIVATE_REPO_USER: ${{ secrets.FR_PRIVATE_REPO_USER }}	
        FR_PRIVATE_REPO_PASSWORD: ${{ secrets.FR_PRIVATE_REPO_PASSWORD }}	
    - name: Build and Test
      run: |
        mvn -ntp verify
      env:	
        FR_PRIVATE_REPO_USER: ${{ secrets.FR_PRIVATE_REPO_USER }}	
        FR_PRIVATE_REPO_PASSWORD: ${{ secrets.FR_PRIVATE_REPO_PASSWORD }}
    - name: Temporarily disable "include administrators" branch protection
      uses: benjefferies/branch-protection-bot@master
      if: always()
      with:
        access-token: ${{ secrets.ACCESS_TOKEN }}
        owner: forgecloud
        repo: ob-tpp
    - name: Deploy
      run: |
        readonly local last_release_commit_hash=$(git log --author="openbankbot" --pretty=format:"%H" -1)
        echo "Last openbankbot commit: ${last_release_commit_hash}"
        echo "Current commit: ${GITHUB_SHA}"
        if [[ "${last_release_commit_hash}" = "${GITHUB_SHA}" ]]; then
          echo "Skipping for openbankbot commit"
          exit 0
        fi
        readonly local branch=${GITHUB_REF##*/}
        echo "Current branch: ${branch}"
        if [[ ! "${branch}" = "master" ]]; then
          echo "Skipping for ${branch} branch"
          exit 0
        fi
        git checkout ${GITHUB_REF##*/}
        git reset --hard ${GITHUB_SHA}
        curl https://raw.githubusercontent.com/ForgeCloud/ob-release/master/src/release.sh > $HOME/release.sh
        bash $HOME/release.sh $M2_HOME/repository
      env:
        FR_PRIVATE_REPO_USER: ${{ secrets.FR_PRIVATE_REPO_USER }}
        FR_PRIVATE_REPO_PASSWORD: ${{ secrets.FR_PRIVATE_REPO_PASSWORD }}
        GITHUB_GPG_KEY: ${{ secrets.GITHUB_GPG_KEY }}
        GITHUB_GPG_KEY_ID: ${{ secrets.GITHUB_GPG_KEY_ID }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    - name: Enable "include administrators" branch protection
      uses: benjefferies/branch-protection-bot@master
      if: always()
      with:
        access-token: ${{ secrets.ACCESS_TOKEN }}
        owner: forgecloud
        repo: ob-tpp
