name: merge-master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: /home/runner/work/_temp/_github_home/.m2/repository
          key: ${{ runner.os }}-maven-mm-${{ hashFiles('**/pom.xml') }}

      - name: Set up maven settings file with creds for Bintray
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          architecture: x64
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Create Package
        uses: benjefferies/create-bintray-package@master
        with:
          bintray-user: openbankingtoolkit
          bintray-token: ${{ secrets.BINTRAY_API_KEY }}

          owner: openbanking-toolkit
          repo: OpenBankingToolKit

          package-name: openbanking-tpp
          package-description: TPP sample app used to simulate a TPP
          package-url: https://github.com/OpenBankingToolkit/openbanking-tpp
          package-license: Apache-2.0

      - name: Temporarily disable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          enforce_admins: false

      - name: Release
        uses: bohocode/github-actions-maven-release@master
        with:
          gpg-enabled: "true"
          gpg-key-id: ${{ secrets.GITHUB_GPG_KEY_ID }}
          gpg-key: ${{ secrets.GITHUB_GPG_KEY }}

          maven-local-repo-path: /github/home/.m2/repository

          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -Ddockerfile.skip -DskipITs -DdockerCompose.skip"
          maven-repo-server-id: bintray-openbankingtoolkit-OpenBankingToolkit
          maven-repo-server-username: openbankingtoolkit
          maven-repo-server-password: ${{ secrets.BINTRAY_API_KEY }}

          git-release-bot-name: "fropenbanking"
          git-release-bot-email: "obst@forgerock.com"

          access-token: ${{ secrets.ACCESS_TOKEN }}

      - name: Enable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          enforce_admins: true
